### PR TITLE
Create locales-es-MX.xml

### PR DESCRIPTION
**Pull request by natch-nacht**
For use in Mexico.

### CODE REVIEW

**Comment by rmzelle** [comment]
@adam3smith, can you take a brief look? Looks good to me: https://www.diffchecker.com/r2go2zet

**Comment by adam3smith** [comment]
thanks!

**Comment by rmzelle** [comment]
(and this continues from #106 and #107)

**Comment by rmzelle** [comment]
(oh, and @adam3smith, we should make sure to update https://github.com/citation-style-language/locales/blob/master/locales.json and https://github.com/citation-style-language/locales/wiki when accepting new locales (I'll do that now); and verify that the language tag is correct, which it seems to be per http://r12a.github.io/apps/subtags/)

**Comment by rmzelle** [comment]
Added to locales.json: https://github.com/citation-style-language/locales/commit/17bc27f4a1835b9f23e5daea98fb61ee2af94072

**Pull request merged**
