### PR TITLE
Update locales-fr-FR.xml

### PR DESCRIPTION
**Pull request by POBrien333**
Just came across this working on a custom style. I do not think "in" is French at all.

## CSL Locales Pull Request Template

You're about to create a pull request to the CSL locales repository.
If you haven't done so already, see <http://docs.citationstyles.org/en/stable/translating-locale-files.html> for instructions on how to translate CSL locale files, and <https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md> on how to submit your changes.
In addition, please fill out the pull request template below.

### Description

Briefly describe the changes you're proposing.

### Checklist

- [ ] Check that you're listed as a `<translator>` in the `<info>` block at the beginning of the file.

### CODE REVIEW

**Comment by adam3smith** [comment]
I think that is on purpose -- my recollection is that French academics more commonly use the Latin "in" (which happens to be the same as the English one). "dans" is in the French Canadian locale: https://github.com/citation-style-language/locales/blob/master/locales-fr-CA.xml#L85

**Comment by bwiernik** [comment]
Do we have a French contributor we can verify with?

**Comment by POBrien333** [comment]
Maybe @fflamerie or @gracile-fr would know?

**Comment by bwiernik** [comment]
I checked four continental French and Belgian psychology journals and they all used "In"

**Comment by POBrien333** [comment]
Ok, thank you so much. I guess we can close this as a false alarm. :)

**Pull request closed without merging**
