### PR TITLE
Rename "figure" and "sub verbo" for 1.0.2

### PR DESCRIPTION
**Pull request by bwiernik**
Rename these terms. Should be the only change needed for validation on CSL 1.0.2

### CODE REVIEW

**Comment by bdarcus** [comment]
There are a bunch of errors like this:

```console
locales-af-ZA.xml:105:4: error: attribute ^name with invalid value "figure-locator"
```

**Comment by adam3smith** [comment]
Huh, that suggests something wrong with the schema? We added that, no?

**Comment by bwiernik** [comment]
Is it validating against 1.0.1 not 1.0.2?

**Comment by bwiernik** [comment]
It's definitely `sub-verbo` in the terms schema : https://github.com/citation-style-language/schema/blob/master/schemas/styles/csl-terms.rnc and https://github.com/citation-style-language/schema/blob/v1.0.2/schemas/styles/csl-terms.rnc

@bdarcus Did you somehow validate against 1.0.1 instead of 1.0.2?

**Comment by bdarcus** [comment]
> Huh, that suggests something wrong with the schema? We added that, no?

"sub-verbo" is correct, but "figure-locator"?

Also, I can't find any record of "figure-locator", and it looks odd to me alongside the other terms.

> @bdarcus Did you somehow validate against 1.0.1 instead of 1.0.2?

I was validating using the master branch. Shouldn't that be correct? It's not, but ...

**Comment by bwiernik** [comment]
figure-locator because there is also a term for the item type figure

**Comment by bwiernik** [comment]
What is the validation command you ran @bdarcus ?

**Comment by adam3smith** [comment]
I was only tangentially involved in the discussion, but this sounds right to me. We also don't have page and page-locator

**Comment by bwiernik** [comment]
Closing this in favor of https://github.com/citation-style-language/locales/pull/230

**Comment by denismaier** [comment]
Yes. I also think we don't necessarily need figure-locator. I've included it solely for the sake of consistency.

**Pull request closed without merging**
