### PR TITLE
translate locales-de-DE.xml for new CSL 1.0.2 terms

### PR DESCRIPTION
**Pull request by POBrien333**
## CSL Locales Pull Request Template

You're about to create a pull request to the CSL locales repository.
If you haven't done so already, see <http://docs.citationstyles.org/en/stable/translating-locale-files.html> for instructions on how to translate CSL locale files, and <https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md> on how to submit your changes.
In addition, please fill out the pull request template below.

### Description

Briefly describe the changes you're proposing.

### Checklist

- [x] Check that you're listed as a `<translator>` in the `<info>` block at the beginning of the file.

### CODE REVIEW

**Comment by POBrien333** [comment]
@adam3smith hab das hier noch nie wirklich gemacht, aber kannst du mal schauen, ob das einigermassen passt? Dann kann ich CH und AT auch noch machen. :)

**Comment by bwiernik** [comment]
This looks okay to me

**Comment by POBrien333** [comment]
Great. I have propagated this over to swiss and austrian german.

**Comment by POBrien333** [comment]
Hi,
Just noticed a missing Translation for a German style I am making. Is there any chance we could get this PR merged, @adam3smith and @bwiernik ?

Thanks a lot :)

**Comment by bwiernik** [comment]
Could you resolve the conflicts @POBrien333

**Comment by bwiernik** [comment]
Thanks!

**Pull request merged**
