### PR TITLE
Update locales-tr-TR.xml

### PR DESCRIPTION
**Pull request by ekizyener**
I have surely done some changes in code for Turkish. Can you fix it? Thanks...

### CODE REVIEW

**Comment by rmzelle** [comment]
@ekizyener, so the only issue is that you have trouble typing smart quotes? If so, you can just copy and paste them from https://github.com/citation-style-language/locales/blob/master/locales-en-US.xml#L65 (or from http://en.wikipedia.org/wiki/Quotation_mark#Summary_table_for_all_languages, or from MS Word).

**Comment by ekizyener** [comment]
As you said i did changes on scripts.
Thanks.

**Comment by adam3smith** [comment]
wonderful, thank you! This will be in the next Zotero release (IIRC that's your ref manager of choice).

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
