### PR TITLE
update for 1.0.2

### PR DESCRIPTION
**Pull request by fflamerie**
## CSL Locales Pull Request Template

You're about to create a pull request to the CSL locales repository.
If you haven't done so already, see <http://docs.citationstyles.org/en/stable/translating-locale-files.html> for instructions on how to translate CSL locale files, and <https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md> on how to submit your changes.
In addition, please fill out the pull request template below.

### Description

- non-breaking spaces before colon and semicolon added
- new terms translated
- some existing translations changed for more consistency with new terms
- not sure about the translation of the locator "elocation"

### Checklist

- [x] Check that you're listed as a `<translator>` in the `<info>` block at the beginning of the file.

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks! Just want to check, is line 72 "in" correct? Not "dans" or "à" ?

**Comment by fflamerie** [comment]
Thanks for your feedback! 

- We have not changed line 72. I do not know what would be the best option. It looks like about 60 styles have set  in a `<locale xml:lang="fr">` `<term name="in">dans</term>`. So I guess the majority (173 styles entitled "français") prefer "in".
- line 160 and 161 : BCE and CE would be more appropriate, I'm sorry I've just checked that.

**Comment by fflamerie** [comment]
I apologize for the delay. 
I have edited the file : line 160 and 161 : translations set back to BCE an CE

**Comment by bwiernik** [comment]
For BCE and CE, shouldn't they be 

1. AEC or AÈC or av. è. c.
2. EC or ÈC or è. c.

Cf. https://fr.wikipedia.org/wiki/%C3%88re_commune

@adam3smith The AD/BC equivalents are most common in French. I see examples of both AEC and av. è. c. in use, with AEC seeming more common. Is it worth recording both long and short forms of these terms in the default locale, or should we just leave changing it to the rare style where that would be necessary?

**Comment by fflamerie** [comment]
I have checked with an ancient history specialist and an historian : 

- ‌av. n. è.
- n. è. 

are more most common, I will update the file consequently. An option without diacritics would be possible, _i. e._ 

- av. n. e.
- n. e.

**Comment by bwiernik** [comment]
Awesome thanks for checking on that

**Pull request merged**
