### PR TITLE
locales-es-MX

### PR DESCRIPTION
**Pull request by natch-nacht**

### CODE REVIEW

**Comment by rmzelle** [comment]
You can't add new terms. You also made a typo in the missing closing tag at `<term name="loc-cit">loc.&#160;cit.<term>`.

The locale file should validate at http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fnatch-nacht%2Flocales-es-MX.xml%2Flocales-es-MX%2Flocales-es-MX.xml&version=1.0.1

**Comment by natch-nacht** [comment]
Hello,

I’m working on the csl code for my workplace at the Escuela Nacional de Antropología e Historia, in Mexico City, for it used with Mendeley, Zotero and Papers as well. In Mexico we use some terms that are not on the list, others with another meaning.
for example:

art. cit, witch mean "cited article"
loc. cit. or locus citatum,  witch mean "in the cited place”, and different to op. cit.
id. or idem. for  identical references, different to ibid. or ibidem
videtur, witch mean “confront"



I understand when you said I can’t add new terms at locales-xml file, but i the question is, can I include this terms in the csl code?

for example:

<locale xml:lang="es-MX”>
  <terms>	
    <term name=“art-cit”>art.&#160;cit.</term>
    <term name=“loc-cit”>loc.&#160;cit.</term>
    <term name="idem">id.</term>
    <term name=“videtur”>
      <single>véase</single>
      <multiple>véanse</multiple></term>
  	</terms>
</locales>



 Also, I need some of the therms in plural which are not present in the locales-es-CL.xml 

Thanks for everything.

Regards.




--
Antrop. Fís. Juan Ignacio Flores Salgado
Departamento de Publicaciones,
Escuela Nacional de Antropología e Historia
natch.nacht@gmail.com

**Comment by rmzelle** [comment]
> can I include this terms in the csl code

You can print verbatim text in styles with `<text value="art.&#160;cit."/>.

> Also, I need some of the therms in plural which are not present in the locales-es-CL.xml

I think you're generally free to define single and plural forms of terms.

**Comment by adam3smith** [comment]
Also, I'm wondering to what extent terms like idem and loc cit are going to be helpful since CSL doesn't have the functionality for their use.

**Pull request closed without merging**
