### PR TITLE
Update locales-de-DE.xml

### PR DESCRIPTION
**Pull request by tillheilmann**
Added (non-breaking) space to terms "ad" and "bc"

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle -- just want to confirm with you that you agree this is right in the locale (I told Till it is): The English 40bc is 40 v. Chr. in German, so it makes sense to me to code the space into the term.

**Comment by rmzelle** [comment]
@adam3smith, do most style guides not use a separating space? E.g. https://en.wikipedia.org/wiki/Anno_Domini does ("AD 525" and "1 BC")

@tillheilmann, have you confirmed that this change actually works? (in Zotero, Mendeley, or something else)

**Comment by adam3smith** [comment]
you're right. Chicago Manual adds a space, too. @fbennett do you have any recollection on why citeproc-js doesn't add a space between year and BC/AD terms?

**Comment by rmzelle** [comment]
> do you have any recollection on why citeproc-js doesn't add a space between year and BC/AD terms?

Maybe because we wrote it that way in the spec? :)

http://docs.citationstyles.org/en/stable/specification.html#ad-and-bc says

> The “ad” term (Anno Domini) is automatically appended to positive years of less than four digits (e.g. “79” becomes “79AD”). The “bc” term (Before Christ) is automatically appended to negative years (e.g. “-2500” becomes “2500BC”).

As long as the CSL processors don't trim white-space characters defined in the term definitions, this is probably the right solution, since it allows for the choice between regular and non-breaking delimiting spaces, as proposed in this PR.

**Comment by adam3smith** [comment]
good point -- we're taking these then, yes?

**Comment by rmzelle** [comment]
Could wait for Frank to chime in, but otherwise yes.

**Comment by tillheilmann** [comment]
@rmzelle, the change of terms (with added non-breaking spaces) works for me if I redefine the terms in the header of my custom CSL files and produce output with Zotero (4.0) on my Mac. I have not tried other versions/programs/OSs.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
