### PR TITLE
Update locales-pt-BR.xml

### PR DESCRIPTION
**Pull request by Eskeminha**
### Description

Updated a lot of Locales. FYI, there are a lot of portguese terms that have no short forms, if you want me to, I can change the ones for their normal use.

### CODE REVIEW

**Comment by bwiernik** [comment]
@adam3smith for terms that don't have a short form in a langauage, I'm thinking it would be easier to maintain to duplicate the long term in the short form. That way we know it's intentional and not missing. What do you think?

**Comment by adam3smith** [comment]
> @adam3smith for terms that don't have a short form in a langauage, I'm thinking it would be easier to maintain to duplicate the long term in the short form. That way we know it's intentional and not missing. What do you think?

Agreed. Will also probably make scripting any bulk updates easier

**Comment by bwiernik** [comment]
@Eskeminha for any terms that don't have a short form, could you add short forms with the same text as the long form?

Thanks so much for your contribution!

**Comment by Eskeminha** [comment]
@bwiernik done.

I just have a final question about one thing, this one:

`218 	<term name="canon">			 
      		<single>canon</single>
		<multiple>canons</multiple>						 
	</term>`
	
Are these related to the biblical canons, or what? I am trying to figure out so I can check for the correct translation.

**Comment by bwiernik** [comment]
Yes, biblical canons and similar for other classic works

**Comment by Eskeminha** [comment]
> Yes, biblical canons and similar for other classic works

Ok, lemme do this final change then.

**Comment by bwiernik** [comment]
@Eskeminha did you intend to close this?

**Comment by Eskeminha** [comment]
Sorry, was cleaning some repos and prob this one went with it :(

**Comment by Eskeminha** [comment]
@bwiernik Do you want me to recreate it, or can you still merge this?

**Comment by bwiernik** [comment]
Can you recreate it?

**Comment by Eskeminha** [comment]
Sure I can

**Pull request closed without merging**
