### PR TITLE
Update locales-it-IT.xml

### PR DESCRIPTION
**Pull request by ezellohar**
## CSL Locales Pull Request Template

You're about to create a pull request to the CSL locales repository.
If you haven't done so already, see <http://docs.citationstyles.org/en/stable/translating-locale-files.html> for instructions on how to translate CSL locale files, and <https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md> on how to submit your changes.
In addition, please fill out the pull request template below.

### Description

Translated all untranslated strings, fixed bad translations, and made the whole more coherent with Zotero item types.

### Checklist

- [x] Check that you're listed as a `<translator>` in the `<info>` block at the beginning of the file.

### CODE REVIEW

**Comment by adam3smith** [comment]
As per the specs, `gender` is only used for ordinal numbers yes.

**Comment by ezellohar** [comment]
Removed the two extra strings, it can be merged now :)

**Comment by denismaier** [comment]
@adam3smith Ok if this is merged?

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
