### PR TITLE
Update locales-ru-RU.xml

### PR DESCRIPTION
**Pull request by myurkin**
Translating new English terms and implementing gender-specific ordinals.
Unfortunately, I am not aware of any way to automatically test the locale file, as it is done for styles.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks!
http://validator.citationstyles.org/
works for style files, too. See if that helps you figure out the problems here, otherwise we'll take a closer look later.

**Comment by rmzelle** [comment]
See http://citationstyles.org/downloads/specification.html#gender-specific-ordinals and http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fmyurkin%2Flocales%2Fmaster%2Flocales-ru-RU.xml&version=1.0.1 .

The problem is that you defined the gender for terms that don't have a matching "number variable".

**Comment by myurkin** [comment]
I have fixed the errors. 
As a side note for future development - it seems logical to make all locator terms gender-assignable, since ordinal numbers may potentially be used in locators (which are manually entered in Word), e.g. Authors, Book, Publisher, (year). (2nd chapter, 37th page).

**Comment by adam3smith** [comment]
thanks! Makes sense re: locators. @rmzelle -- am I missing something?

**Comment by rmzelle** [comment]
Can't find a fault in the logic in that.

**Pull request merged**
