### PR TITLE
Create Latin translation

### PR DESCRIPTION
**Pull request by adunning**
This is meant to support style files for series such as Corpus Christianorum, <http://www.corpuschristianorum.org/authors.html>. I've translated all the terms, but many will never come up in practice. I'm not aware of a proper Latin citation guide, and would be delighted to see any corrections.

### CODE REVIEW

**Comment by adam3smith** [comment]
It's probably not going to see a ton of use, but I'm pretty psyched we have this. Thanks!

**Comment by adunning** [comment]
Thank you! It was quite fun to put together.

**Comment by rmzelle** [comment]
Hey both, I'm a bit late to the party, but it doesn't look like "la-LA" is the correct locale code. Per https://r12a.github.io/app-subtags/, "la-LA" appears to stand for Latin in Laos. Since Latin probably doesn't have a clearly defined geographical area, I suggest trimming the locale code to just "la".

**Comment by adunning** [comment]
I ought to have remembered. Sorry about that!

**Comment by adunning** [comment]
This is fixed in #188.

**Pull request merged**
