### PR TITLE
Create locales-gl-GL.xml

### PR DESCRIPTION
**Pull request by mmgn897**
Translation to [Galician](https://en.wikipedia.org/wiki/Galician_language)

### CODE REVIEW

**Comment by manuelmagan** [comment]
Could someone help me with this issue?

**Comment by adam3smith** [comment]
Thanks -- ignore the failing test. 
I'm pretty sure GL as a country code doesn't exist. Would it be OK to use the standard gl-ES (see e.g. https://www.localeplanet.com/icu/gl-ES/index.html ) or is that politically problematic?

**Comment by manuelmagan** [comment]
Thanks! Yes, gl-ES is okay.

**Comment by manuelmagan** [comment]
Hello. Any news about this pull? Should I change something?

**Pull request closed without merging**
