### PR TITLE
Update locales-fa-IR.xml

### PR DESCRIPTION
**Pull request by hamedheydari**

### CODE REVIEW

**Comment by adam3smith** [comment]
@abdealikhurrum since we don't speak Farsi, we always like to get a second opinion. Does this look correct to you?

**Comment by hamedheydari** [comment]
@adam3smith How long should I wait for him? And besides, basically, I think he's not an Iranian and doesn't speak Farsi.

**Comment by abdealikhurrum** [comment]
Sorry for not replying sooner, I hadn't been checking my email...But yes,
I'm not Iranian and not too familiar with Farsi. But I do know a few people
who do, so if you need any help, I can ask them.

**Comment by hamedheydari** [comment]
@abdealikhurrum Thank You. I really appreciate you for contributing on this subject. but it would be better if this changes approved.

**Comment by rmzelle** [comment]
Okay, thanks. I went ahead and merged it.

**Comment by hamedheydari** [comment]
@rmzelle Thank You.

**Pull request merged**
