### PR TITLE
Add badges to README.md

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by rmzelle** [comment]
Also see https://github.com/citation-style-language/journals/pull/24 and https://github.com/citation-style-language/styles/pull/2432

**Comment by rmzelle** [comment]
Thanks! Now we just have to remember to update the counter when we add additional locales.

**Comment by zuphilip** [comment]
Yes! On the other side, nobody will check the count accurately 🛂 and the number is already high to convince 🎯 ;-)

**Comment by rmzelle** [comment]
Convince darts/targets?

**Pull request merged**
